name: ig-public_v3
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.4.1+46
ios_version: 8.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_flavorizr: ^2.1.5
  http: ^0.13.5
  kakao_flutter_sdk: ^1.4.0
  flutter_facebook_auth: ^5.0.7
  flutter_naver_login: ^1.8.0
  google_sign_in: ^5.4.4
  sign_in_with_apple: ^4.3.0 
  flutter_screenutil: ^5.6.1
  flutter_svg: ^2.0.3
  auto_size_text: ^3.0.0
  intl: ^0.17.0
  http_interceptor: ^1.0.2
  firebase_core: ^2.9.0
  firebase_messaging: ^14.4.0
  flutter_local_notifications: ^13.0.0
  path_provider: ^2.0.14
  channel_talk_flutter: ^2.4.0
  crypto: ^3.0.2
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.1.0
  flutter_html: ^3.0.0-alpha.6
  image_picker: ^0.8.7+4
  permission_handler: ^10.2.0
  oktoast: ^3.3.1
  flutter_rating_bar: ^4.0.1
  path_drawing: ^1.0.1
  iamport_flutter: ^0.10.0
  url_launcher: ^6.1.11
  yaml: ^3.1.2
  contacts_service: ^0.6.3
  firebase_dynamic_links: ^5.3.1
  flutter_sms: ^2.3.3
  app_links: ^3.4.3
  share_plus: ^7.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/img/launcher-logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/icon/
    - assets/splash/
    - pubspec.yaml

  fonts:
    - family: NanumSquareNeo
      fonts:
        - asset: assets/font/NanumSquareNeoOTF-Lt.otf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
